#!/bin/sh

#
# Copyright (c) 2019 Carnegie Mellon University,
# Copyright (c) 2019 Triad National Security, LLC, as operator of
#     Los Alamos National Laboratory.
#
# All rights reserved.
#
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file. See the AUTHORS file for names of contributors.
#

#
# ensure-autogen  ensure autotool-based packages have a configure file
# 26-Sep-2016  chuck@ece.cmu.edu
#

if [ -f ./configure ]; then
    echo configure already present, no action required
    exit 0
fi

echo ensure-autogen: running $*
exec $*
